name: wbw_dictionaries
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"
# homepage:
environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  archive: ^4.0.7
  csv: ^6.0.0
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  is_dart_empty_or_not: ^0.2.3
  provider: ^6.1.5+1
  russian_words: ^0.2.0
  sembast: ^3.8.5+1
  sembast_web: ^2.4.2
  serverpod_flutter: ^2.9.1
  tar: ^2.0.1
  universal_io: ^2.2.2
  wbw_client:
  wbw_core:
  wbw_locale:
  xsoulspace_foundation: ^0.3.0
  xsoulspace_ui_foundation: ^0.3.1
dev_dependencies:
  build_runner: ^2.9.0
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2

# For information see the following page:
# https://pub.dev/packages/flutter_gen
flutter_gen:
  output: lib/src/gen/

  assets:
    enabled: true
    outputs:
      directory_path_enabled: true
      package_parameter_enabled: true

  integrations:
    image: true
    flutter_svg: true
    rive: true

  fonts:
    enabled: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/archives/
    - assets/src/
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
