name: pixel_art_creator
description: design ui kit
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  go_router: ^15.1.3
  provider: ^6.1.5

flutter:
  uses-material-design: true
