name: wbw_ui_kit
description: design ui kit
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"

resolution: workspace

dependencies:
  animate_do: ^4.2.0
  blur: ^4.0.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_hooks: ^0.21.2
  flutter_portal: ^1.1.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  life_hooks: ^0.1.1
  provider: ^6.1.5
  recase: ^4.1.0
  rive: ^0.13.20
  sliver_tools: ^0.2.12
  tap_builder: ^0.5.0
  wbw_core:
  wbw_locale:
  xsoulspace_foundation: ^0.2.0

dev_dependencies:
  analyzer: ^7.4.5
  build_runner: ^2.5.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # assets:
  #   - assets/images/
  # To add assets to your application, add an assets section, like this:
  assets:
    - google_fonts/
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # fonts:
  #   - family: la_icons
  #     fonts:
  #       - asset: packages/la_design_core/fonts/la_icons.ttf
