name: wbw_core
description: core to use inside app
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  bloc: ^9.1.0
  collection: ^1.19.1
  english_words: ^4.0.0
  equatable: ^2.0.7
  firebase_analytics: ^12.0.3
  firebase_analytics_web: ^0.6.0+3
  firebase_core: ^4.2.0
  firebase_core_web: ^3.2.0
  firebase_crashlytics: ^5.0.3
  flame: ^1.32.0
  flame_bloc: ^1.12.17
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3+1
  flutter_keyboard_visibility: ^6.0.0
  flutter_portal: ^1.1.4
  freezed_annotation: ^3.1.0
  from_json_to_json: ^0.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  life_hooks: ^0.2.0
  logger: ^2.6.2
  map_editor:
  path_to_regexp: ^0.4.0
  provider: ^6.1.5+1
  quiver: ^3.2.2
  russian_words: ^0.2.0
  shared_preferences: ^2.5.3
  universal_io: ^2.2.2
  uuid: ^4.5.1
  wbw_client:
  wbw_dictionaries:
  wbw_locale:
  web: ^1.1.1
  window_manager: ^0.4.3
  xsoulspace_foundation: ^0.3.0
  xsoulspace_ui_foundation: ^0.3.1

dev_dependencies:
  analyzer: ^8.4.0
  build_runner: ^2.9.0
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2

flutter_gen:
  output: lib/src/gen/

  assets:
    enabled: true
    outputs:
      directory_path_enabled: true
      package_parameter_enabled: true

  integrations:
    image: true
    flutter_svg: true
    rive: false

  fonts:
    enabled: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # fonts:
  #   - family: Raleway
  #     fonts:
  #       - asset: assets/fonts/Raleway-Regular.ttf
  #       - asset: assets/fonts/Raleway-Italic.ttf
  #         style: italic
  assets:
    - assets/
    - assets/dictionaries/
    - assets/levels/
# assets:
#   - assets/images/
# fonts:
#   - family: asgard_icons
#     fonts:
#       - asset: packages/la_design_core/fonts/asgard_icons.ttf
#   - family: Poppins
#     fonts:
#       - asset: packages/la_design_core/fonts/Poppins-Regular.ttf
#         weight: 400
#       - asset: packages/la_design_core/fonts/Poppins-Bold.ttf
#         weight: 700
