name: map_editor
description: A new Flutter package project.
version: 0.0.1
publish_to: none

# publish_to: "none"
# homepage:
environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  animate_do: ^4.2.0
  bloc: ^9.1.0
  blur: ^4.0.2
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  file_picker: ^10.3.3
  firebase_analytics: ^12.0.3
  firebase_analytics_web: ^0.6.0+3
  firebase_core: ^4.2.0
  firebase_core_web: ^3.2.0
  firebase_crashlytics: ^5.0.3
  flame: ^1.32.0
  flame_bloc: ^1.12.17
  flame_fire_atlas: ^1.8.11
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.4
  flutter_svg: ^2.2.1
  freezed_annotation: ^3.1.0
  from_json_to_json: ^0.3.0
  gap: ^3.0.1
  google_fonts: ^6.3.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  life_hooks: ^0.2.0
  logger: ^2.6.2
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  recase: ^4.1.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  tiled: ^0.11.1
  universal_io: ^2.2.2
  url_launcher: ^6.3.2
  wbw_core:
  wbw_locale:
  wbw_ui_kit:
  xsoulspace_foundation: ^0.3.0
  xsoulspace_ui_foundation: ^0.3.1
dev_dependencies:
  analyzer: ^8.4.0
  build_runner: ^2.9.0
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2

flutter_gen:
  output: lib/generated/

  assets:
    enabled: true
    outputs:
      directory_path_enabled: true
      package_parameter_enabled: false

  integrations:
    image: true
    flutter_svg: true
    rive: true

  fonts:
    enabled: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: false
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/preview/
    - assets/images/preview/colourful/
    - assets/images/preview/white_black/
    - assets/images/preview/evening/
    - assets/images/tilesets/
    - assets/images/tilesets/white_black/
    - assets/images/tilesets/evening/
    - assets/images/cursors/
    - assets/images/cursors/cursor/
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
